CREATE TABLE useri (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username varchar,
  email varchar,
  parola varchar,
  status bool,
  data_inregistrare date,
  avatar varchar,
  is_email_verified boolean
);

CREATE TABLE token(
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES  useri(id),
    token varchar(128),
    type smallint
);

CREATE TABLE roles (
  name varchar PRIMARY KEY
);

CREATE TABLE users_roles(
  user_id integer REFERENCES useri(id),
  role_id varchar REFERENCES roles(name)
);

CREATE TABLE producatori (
  id integer PRIMARY KEY REFERENCES useri(id) ON DELETE CASCADE,
  nume varchar,
  prenume varchar,
  adresa varchar,
  telefon varchar,
  regiune varchar
);

CREATE TABLE clienti (
  id integer PRIMARY KEY REFERENCES useri(id) ON DELETE CASCADE,
  nume varchar,
  telefon varchar,
  prenume varchar
);

CREATE TABLE admini (
  id integer PRIMARY KEY REFERENCES useri(id) ON DELETE CASCADE,
  nume varchar,
  prenume varchar
);

CREATE TABLE comenzi (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_client integer NOT NULL REFERENCES clienti(id) ,
  data_efectuarii date,
  status_comanda      SMALLINT,
  adresa_livrare_id   INTEGER,
  adresa_facturare_id INTEGER,
  metoda_livrare_id   INTEGER,
  metoda_plata        SMALLINT,
  observatii          VARCHAR(255)
);


CREATE TABLE adresa
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nume_complet      VARCHAR(255),
    telefon           VARCHAR(255),
    strada_nume_numar VARCHAR(255),
    localitate        VARCHAR(255),
    judet             VARCHAR(255),
    cod_postal        VARCHAR(255),
    CONSTRAINT pk_adresa PRIMARY KEY (id)
);


CREATE TABLE metoda_livrare_pret
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    metoda_livrare SMALLINT,
    pret           DOUBLE PRECISION,
    CONSTRAINT pk_metodalivrarepret PRIMARY KEY (id)
);

ALTER TABLE metoda_livrare_pret
    ADD CONSTRAINT uc_metodalivrarepret_metodalivrare UNIQUE (metoda_livrare);

ALTER TABLE comenzi
    ADD CONSTRAINT FK_COMENZI_ON_ADRESAFACTURARE FOREIGN KEY (adresa_facturare_id) REFERENCES adresa (id);

ALTER TABLE comenzi
    ADD CONSTRAINT FK_COMENZI_ON_ADRESALIVRARE FOREIGN KEY (adresa_livrare_id) REFERENCES adresa (id);

ALTER TABLE comenzi
    ADD CONSTRAINT FK_COMENZI_ON_ID_CLIENT FOREIGN KEY (id_client) REFERENCES clienti (id);

ALTER TABLE comenzi
    ADD CONSTRAINT FK_COMENZI_ON_METODALIVRARE FOREIGN KEY (metoda_livrare_id) REFERENCES metoda_livrare_pret (id);


CREATE TABLE produse (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nume varchar,
  categorie varchar
);

CREATE TABLE pachete (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_producator integer NOT NULL references producatori(id) ON DELETE CASCADE,
  nume varchar,
  imagine varchar,
  descriere varchar(1000),
  pret_total float,
  pret_abonament float,
  e_abonament boolean DEFAULT false,
  frecventa_livrare integer
);

CREATE TABLE subscriptii (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_client integer NOT NULL references clienti(id),
  id_pachet integer NOT NULL references pachete(id),
  data_inceput date,
  frecventa integer,
  status varchar
);

CREATE TABLE produs_producator (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_producator integer NOT NULL REFERENCES producatori(id),
  id_produs integer NOT NULL REFERENCES produse(id),
  cantitate float,
  unitate_masura varchar,
  pret float,
  imagine varchar,
  denumire_personalizata varchar
);


CREATE TABLE pachet_produs (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_pachet integer NOT NULL references pachete(id),
  id_produs integer NOT NULL references produs_producator(id),
  cantitate float,
  pret_unitar float
);

CREATE TABLE comanda_produs (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_comanda integer NOT NULL REFERENCES comenzi(id),
  id_produs integer NOT NULL REFERENCES  produs_producator(id),
  cantitate float,
  pret_unitar float
);



CREATE TABLE comanda_pachet (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_comanda integer NOT NULL references comenzi(id),
  id_pachet integer NOT NULL references pachete(id),
  cantitate float,
  pret_unitar float
);
